apiVersion: v1
kind: Service
metadata:
  name: event-frontend-service
spec:
  selector:
    app: event-frontend
  ports:
    - protocol: TCP
      port: 80         # The internal port other services/ingress will ping
      targetPort: 3000 # The port your Next.js container is listening on
  type: ClusterIP      # Accessible only from inside the cluster (the ingress will expose it to the internet)
