import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/common/navigationbar";
import Providers from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Providers>
        <NavigationBar />
        <body className="min-h-full flex flex-col">{children}</body>
        <footer className="text-center py-6 text-gray-500 bg-gray-900 text-sm">
          © {new Date().getFullYear()} EventNet. All rights reserved.
        </footer>
      </Providers>
    </html>
  );
}
