apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-deployment
  labels:
    app: booking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: eventregistryhiran01.azurecr.io/booking-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: DB_HOST
          value: "booking-postgres-pasindu.postgres.database.azure.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "booking_service_db"
        - name: DB_USER
          value: "dbadmin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: booking-service-secrets
              key: DB_PASSWORD
        - name: DB_SSL
          value: "true"
        - name: EVENT_SERVICE_BASE_URL
          value: "http://event-service:5002/api"
        - name: USER_SERVICE_BASE_URL
          value: "http://user-service:80/api"
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: booking-service-secrets
              key: RABBITMQ_URL
        - name: PAYMENT_RESULT_QUEUE_NAME
          value: "payment-result-queue"
        - name: BOOKING_EXPIRY_MINUTES
          value: "10"
        livenessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 10
